### ISSUE TITLE
FEATURE: Repeat the Deploy step in Github Actions to avoid failures

### ISSUE THREAD

**Issue by Division7** [ucsb-cs156/proj-dining#48]
Many of the Github Actions scripts have a Deploy step as their final step; in this final step, they deploy some content to the gh-pages branch to publish it to the Github Pages site for the repo.

These steps often fail due to contention over the gh-pages branch, and have to be manually re-run.  This slows down development, since these CI/CD failures are false alarms.

In this Issue, we wrap these steps in a Github Action that will repeat the step several times before failing after a delay.

# Example

This commit shows the before and after of this change:

https://github.com/ucsb-cs156/proj-courses/commit/bec86701b5447218ab5ac39697a5702d6b73de16

The intention is to apply this transformation to each of the workflows that uses the 

Old code:

```yml
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/site/jacoco # The folder where mvn puts the files
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: ${{env.prefix}}jacoco # The folder that we serve our files from
```

New Code:

```yml
    - name: Deploy 🚀    
      if: always() # always upload artifacts, even if tests fail
      uses: Wandalen/wretry.action@master
      with:
        action: JamesIves/github-pages-deploy-action@v4
        attempt_limit: 3
        attempt_delay: 5000
        with: |
          branch: gh-pages # The branch the action should deploy to.
          folder: target/site/jacoco # The folder where mvn puts the files
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: ${{env.prefix}}jacoco # The folder that we serve our files from
```
